spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:\Users\jstol\IdeaProjects\todo-app\tododb'
  jpa:
    hibernate:
      ddl-auto: validate
management:
    endpoints:
      web:
        exposure:
          include: '*'

